const countryRegionMapping: { [key: string]: string } = {
    Afghanistan: 'Asia',
    Armenia: 'Asia',
    Azerbaijan: 'Asia',
    Bahrain: 'Asia',
    Bangladesh: 'Asia',
    Bhutan: 'Asia',
    Brunei: 'Asia',
    Cambodia: 'Asia',
    China: 'Asia',
    India: 'Asia',
    Indonesia: 'Asia',
    Iran: 'Asia',
    Iraq: 'Asia',
    Israel: 'Asia',
    Japan: 'Asia',
    Jordan: 'Asia',
    Kuwait: 'Asia',
    Kyrgyzstan: 'Asia',
    Laos: 'Asia',
    Lebanon: 'Asia',
    Malaysia: 'Asia',
    Maldives: 'Asia',
    Mongolia: 'Asia',
    Myanmar: 'Asia',
    Nepal: 'Asia',
    "North Korea": 'Asia',
    Oman: 'Asia',
    Pakistan: 'Asia',
    Palestine: 'Asia',
    Philippines: 'Asia',
    Qatar: 'Asia',
    "Saudi Arabia": 'Asia',
    Singapore: 'Asia',
    "South Korea": 'Asia',
    "Sri Lanka": 'Asia',
    Syria: 'Asia',
    Taiwan: 'Asia',
    Tajikistan: 'Asia',
    Thailand: 'Asia',
    "Timor-Leste": 'Asia',
    Turkey: 'Asia',
    Turkmenistan: 'Asia',
    "United Arab Emirates": 'Asia',
    Uzbekistan: 'Asia',
    Vietnam: 'Asia',
    Yemen: 'Asia',
  
    // Europe
    Albania: 'Europe',
    Andorra: 'Europe',
    Austria: 'Europe',
    Belarus: 'Europe',
    Belgium: 'Europe',
    "Bosnia and Herzegovina": 'Europe',
    Bulgaria: 'Europe',
    Croatia: 'Europe',
    Cyprus: 'Europe',
    "Czech Republic": 'Europe',
    Denmark: 'Europe',
    Estonia: 'Europe',
    Finland: 'Europe',
    France: 'Europe',
    Georgia: 'Europe',
    Germany: 'Europe',
    Greece: 'Europe',
    Hungary: 'Europe',
    Iceland: 'Europe',
    Ireland: 'Europe',
    Italy: 'Europe',
    Kazakhstan: 'Europe',
    Kosovo: 'Europe',
    Latvia: 'Europe',
    Liechtenstein: 'Europe',
    Lithuania: 'Europe',
    Luxembourg: 'Europe',
    Malta: 'Europe',
    Moldova: 'Europe',
    Monaco: 'Europe',
    Montenegro: 'Europe',
    Netherlands: 'Europe',
    "North Macedonia": 'Europe',
    Norway: 'Europe',
    Poland: 'Europe',
    Portugal: 'Europe',
    Romania: 'Europe',
    Russia: 'Europe',
    "San Marino": 'Europe',
    Serbia: 'Europe',
    Slovakia: 'Europe',
    Slovenia: 'Europe',
    Spain: 'Europe',
    Sweden: 'Europe',
    Switzerland: 'Europe',
    Ukraine: 'Europe',
    "United Kingdom": 'Europe',
    "Vatican City": 'Europe',
  
    // Africa
    Algeria: 'Africa',
    Angola: 'Africa',
    Benin: 'Africa',
    Botswana: 'Africa',
    "Burkina Faso": 'Africa',
    Burundi: 'Africa',
    "Cape Verde": 'Africa',
    Cameroon: 'Africa',
    "Central African Republic": 'Africa',
    Chad: 'Africa',
    Comoros: 'Africa',
    Congo: 'Africa',
    Djibouti: 'Africa',
    Egypt: 'Africa',
    "Equatorial Guinea": 'Africa',
    Eritrea: 'Africa',
    Eswatini: 'Africa',
    Ethiopia: 'Africa',
    Gabon: 'Africa',
    Gambia: 'Africa',
    Ghana: 'Africa',
    Guinea: 'Africa',
    "Guinea-Bissau": 'Africa',
    "Ivory Coast": 'Africa',
    Kenya: 'Africa',
    Lesotho: 'Africa',
    Liberia: 'Africa',
    Libya: 'Africa',
    Madagascar: 'Africa',
    Malawi: 'Africa',
    Mali: 'Africa',
    Mauritania: 'Africa',
    Mauritius: 'Africa',
    Morocco: 'Africa',
    Mozambique: 'Africa',
    Namibia: 'Africa',
    Niger: 'Africa',
    Nigeria: 'Africa',
    Rwanda: 'Africa',
    "Sao Tome and Principe": 'Africa',
    Senegal: 'Africa',
    Seychelles: 'Africa',
    "Sierra Leone": 'Africa',
    Somalia: 'Africa',
    "South Africa": 'Africa',
    "South Sudan": 'Africa',
    Sudan: 'Africa',
    Tanzania: 'Africa',
    Togo: 'Africa',
    Tunisia: 'Africa',
    Uganda: 'Africa',
    Zambia: 'Africa',
    Zimbabwe: 'Africa',
  
    // Oceania
    Australia: 'Oceania',
    Fiji: 'Oceania',
    Kiribati: 'Oceania',
    "Marshall Islands": 'Oceania',
    Micronesia: 'Oceania',
    Nauru: 'Oceania',
    "New Zealand": 'Oceania',
    Palau: 'Oceania',
    "Papua New Guinea": 'Oceania',
    Samoa: 'Oceania',
    "Solomon Islands": 'Oceania',
    Tonga: 'Oceania',
    Tuvalu: 'Oceania',
    Vanuatu: 'Oceania',
  
    // Americas
    "Antigua and Barbuda": 'Americas',
    Argentina: 'Americas',
    Bahamas: 'Americas',
    Barbados: 'Americas',
    Belize: 'Americas',
    Bolivia: 'Americas',
    Brazil: 'Americas',
    Canada: 'Americas',
    Chile: 'Americas',
    Colombia: 'Americas',
    "Costa Rica": 'Americas',
    Cuba: 'Americas',
    Dominica: 'Americas',
    "Dominican Republic": 'Americas',
    Ecuador: 'Americas',
    "El Salvador": 'Americas',
    Grenada: 'Americas',
    Guatemala: 'Americas',
    Guyana: 'Americas',
    Haiti: 'Americas',
    Honduras: 'Americas',
    Jamaica: 'Americas',
    Mexico: 'Americas',
    Nicaragua: 'Americas',
    Panama: 'Americas',
    Paraguay: 'Americas',
    Peru: 'Americas',
    "Saint Kitts and Nevis": 'Americas',
    "Saint Lucia": 'Americas',
    "Saint Vincent and the Grenadines": 'Americas',
    Suriname: 'Americas',
    "Trinidad and Tobago": 'Americas',
    "United States": 'Americas',
    Uruguay: 'Americas',
    Venezuela: 'Americas',
  };
  
  export default countryRegionMapping;
  